#!/bin/bash
# $1=iot-gw directory
# $2=result tar file

T=/tmp/.$$.tmp
MODULES=mods

trap "rm -rf '$T'" 0

mkdir -p "$T"/{php,html}
cp "$1"/php/* "$T"/php
cp "$1"/www/* "$T"/html

for md in "$1"/../$MODULES/*/iotgw-*
do
  [ -d "$md" ] || continue
  m="${md%/iotgw-*}"
  mod="${$md##*/iotgw-}"
  [ "$mod" = 'mod' ] && mod="${m##*/}"

  if [ -d "$T/php/$mod" ]
  then
    n=1
    while [ -d "$T/php/$mod.$n" ] ; do let n++ ; done
    mod="$mod.$n"
  fi
  
  echo "IOTGW: $mod"
  cp -a "$md/" "$T/php/$mod" || exit
done

tar -zcvf "$2" -C "$T" .
